### PR TITLE
Changes

### PR DESCRIPTION
**Pull request by zadr**
Fix a bunch of things, memory-related. Also, general code formatting cleanup. I did remove AppiRater and Flurry, so, git revert those commits if you want to keep them in.

### CODE REVIEW

**Comment by ljuba** [comment]
A lot of this looks great. I'm curious, why did you remove the NSLogs? What harm do they do?

**Comment by ljuba** [comment]
Also, don't know how I missed this. I don't think I got an email about this pull request. Sorry about that. Are you coming to the hackathon?

**Comment by ljuba** [comment]
I've integrated a bunch of these commits. THANKS SO MUCH!

**Comment by zadr** [comment]
I removed the NSLog's because Xcode doesn't have a good way to filter logs, and having them in makes it hard to find specific logging information when looking for it.

And what hackathon? I haven't heard anything about one.

**Pull request closed without merging**
